In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("datasets/weather_data.csv")

In [7]:
df

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,moonrise,moonset,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,2009-01-01 00:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,14,19,0,50,0.0,1016,10,10,331,12
1,2009-01-01 01:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,13,21,0,51,0.0,1016,10,10,329,13
2,2009-01-01 02:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,12,22,0,52,0.0,1016,9,10,327,13
3,2009-01-01 03:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,11,23,0,54,0.0,1016,9,10,326,13
4,2009-01-01 04:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,11,21,2,52,0.0,1016,9,10,318,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96427,2020-01-01 19:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,17,11,10,39,0.0,1020,17,10,96,9
96428,2020-01-01 20:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,16,11,9,40,0.0,1021,16,10,97,8
96429,2020-01-01 21:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,16,12,8,41,0.0,1021,16,10,98,8
96430,2020-01-01 22:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,15,11,8,42,0.0,1021,15,10,96,8
96431,2020-01-01 23:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,15,10,7,42,0.0,1022,15,10,94,8

In [8]:
df.head(3)

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,moonrise,moonset,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,2009-01-01 00:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,14,19,0,50,0.0,1016,10,10,331,12
1,2009-01-01 01:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,13,21,0,51,0.0,1016,10,10,329,13
2,2009-01-01 02:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,12,22,0,52,0.0,1016,9,10,327,13